[package]
name = "burger"
version = "0.1.0"
edition = "2021"

[dependencies]
async-lock = "3.2.0"
futures-channel = "0.3.29"
futures-util = "0.3.29"
pin-project-lite = "0.2.13"
tokio = { version = "1.34.0", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread", "time"] }
